
export const supabaseUrl = "https://zoelblemfnxmaatopyst.supabase.co";
export const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvZWxibGVtZm54bWFhdG9weXN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTkwNTAxODIsImV4cCI6MjAzNDYyNjE4Mn0.EsCOLcBllKdi0KSb1UJOLUEn0if9iLJdrTAxtyOA8t0';